// ==========================================================================
// KINTARO FORMULARY — Build Script (plain Node, zero dependencies)
// ==========================================================================
// Reads formulary.csv and emits three artifacts:
//   1. formulary.json  — the data, grouped and flat (for any consumer)
//   2. FORMULARY.md    — category-grouped markdown snapshot (diff-friendly)
//   3. index.html      — self-contained interactive viewer (open in a browser)
//
// Vocabulary + CSV parsing live in lib/vocab.mjs (single source of truth).
// Output is deterministic (no timestamps) so re-runs are byte-identical.
//
//   node scripts/build.mjs      (or: npm run build)

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { FORMULARY_CATEGORIES, PHARMACIES, loadRows } from "../lib/vocab.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CSV_PATH = join(ROOT, "formulary.csv");

function groupByCategory(rows) {
  const out = {};
  for (const c of FORMULARY_CATEGORIES) out[c] = [];
  for (const r of rows) out[r.category].push(r);
  return out;
}

// ── artifact 1: JSON data export ────────────────────────────────────────
function writeJson(rows, byCat) {
  const counts = {};
  for (const c of FORMULARY_CATEGORIES) if (byCat[c].length) counts[c] = byCat[c].length;
  const out = { total: rows.length, counts, by_category: byCat, rows };
  writeFileSync(join(ROOT, "formulary.json"), JSON.stringify(out, null, 2) + "\n");
}

// ── artifact 2: markdown snapshot ───────────────────────────────────────
const mdEsc = (s) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");

function writeMarkdown(rows, byCat) {
  const L = [];
  L.push("# Kintaro Formulary");
  L.push("");
  L.push("> GENERATED by `scripts/build.mjs` from `formulary.csv`. Do not edit by hand — edit the CSV and run `npm run build`.");
  L.push("");
  L.push(`**${rows.length} products** across ${PHARMACIES.length} pharmacies.`);
  L.push("");
  L.push("## Summary");
  L.push("");
  L.push("| Category | Products |");
  L.push("|---|---:|");
  for (const c of FORMULARY_CATEGORIES) if (byCat[c].length) L.push(`| ${c} | ${byCat[c].length} |`);
  L.push(`| **Total** | **${rows.length}** |`);
  L.push("");

  const review = rows.filter((r) => r.tags.split("|").includes("review"));
  if (review.length) {
    L.push("## ⚑ Flagged for review");
    L.push("");
    L.push("Rows whose primary category or classification a human should confirm.");
    L.push("");
    L.push("| Product | Strength | Category | Note |");
    L.push("|---|---|---|---|");
    for (const r of review) L.push(`| ${mdEsc(r.product_name)} | ${mdEsc(r.strength)} | ${r.category} | ${mdEsc(r.notes)} |`);
    L.push("");
  }

  for (const c of FORMULARY_CATEGORIES) {
    const rs = byCat[c];
    if (!rs.length) continue;
    L.push(`## ${c} (${rs.length})`);
    L.push("");
    L.push("| Product | Strength | Form | Package | Pharmacy | SKU | Wholesale | Tags | Notes |");
    L.push("|---|---|---|---|---|---|---:|---|---|");
    for (const r of rs) {
      const cost = r.wholesale_cost ? `$${r.wholesale_cost}` : "";
      L.push(
        `| ${mdEsc(r.product_name)} | ${mdEsc(r.strength)} | ${r.form} | ${mdEsc(r.package)} | ` +
          `${r.pharmacy} | ${mdEsc(r.sku)} | ${cost} | ${mdEsc(r.tags)} | ${mdEsc(r.notes)} |`
      );
    }
    L.push("");
  }
  writeFileSync(join(ROOT, "FORMULARY.md"), L.join("\n"));
}

// ── artifact 3: interactive HTML viewer ─────────────────────────────────
function writeHtml(rows) {
  const data = JSON.stringify(rows).replace(/</g, "\\u003c");
  const cats = JSON.stringify(["All", ...FORMULARY_CATEGORIES.filter((c) => rows.some((r) => r.category === c))]);
  const pharms = JSON.stringify(["All", ...PHARMACIES]);

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Kintaro Formulary</title>
<style>
  :root { color-scheme: light dark; --bg:#fff; --fg:#1a1a1a; --muted:#666; --line:#e5e5e5;
          --accent:#0f7a5a; --chip:#f2f4f3; --head:#fafafa; }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#151716; --fg:#eee; --muted:#9aa; --line:#2c302e; --accent:#4bbf95; --chip:#20241f; --head:#1b1e1c; }
  }
  * { box-sizing: border-box; }
  body { margin:0; font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
         background:var(--bg); color:var(--fg); }
  header { padding:20px 24px 12px; border-bottom:1.5px solid var(--fg); }
  h1 { margin:0; font-size:24px; letter-spacing:-0.02em; }
  .meta { color:var(--muted); margin-top:4px; }
  .controls { display:flex; gap:12px; flex-wrap:wrap; align-items:center; padding:12px 24px; position:sticky; top:0;
              background:var(--bg); border-bottom:1px solid var(--line); z-index:5; }
  input, select { font:inherit; padding:6px 10px; border:1px solid var(--line); border-radius:6px;
                  background:var(--bg); color:var(--fg); }
  input[type=search]{ min-width:220px; flex:1; }
  .tabs { display:flex; gap:6px; flex-wrap:wrap; padding:12px 24px 0; }
  .tab { padding:6px 12px; border:1px solid var(--line); border-radius:999px; cursor:pointer;
         background:var(--chip); color:var(--fg); font-size:13px; }
  .tab.active { background:var(--accent); color:#fff; border-color:var(--accent); }
  .tab .n { opacity:.7; margin-left:6px; font-variant-numeric:tabular-nums; }
  .wrap { padding:12px 24px 60px; overflow-x:auto; }
  table { border-collapse:collapse; width:100%; min-width:760px; }
  th, td { text-align:left; padding:7px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { position:sticky; top:0; background:var(--head); font-size:12px; text-transform:uppercase;
       letter-spacing:.04em; color:var(--muted); cursor:pointer; }
  td.num, th.num { text-align:right; font-variant-numeric:tabular-nums; }
  .mono { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:12px; }
  .tag { display:inline-block; background:var(--chip); border-radius:4px; padding:1px 6px; margin:1px 2px 1px 0;
         font-size:11px; color:var(--muted); }
  .tag.review { background:#fbe5c8; color:#8a5a00; }
  @media (prefers-color-scheme: dark){ .tag.review{ background:#3a2e12; color:#e6b866; } }
  .cat { color:var(--accent); font-weight:600; }
  .empty { color:var(--muted); padding:40px 0; text-align:center; }
</style>
</head>
<body>
<header>
  <h1>Kintaro Formulary</h1>
  <div class="meta"><span id="count"></span> — compounded-medication catalog across ${PHARMACIES.length} pharmacies</div>
</header>
<div class="tabs" id="tabs"></div>
<div class="controls">
  <input type="search" id="q" placeholder="Search product, ingredient, SKU, strength…" />
  <select id="pharm"></select>
  <label class="mono"><input type="checkbox" id="rx" /> Rx only</label>
</div>
<div class="wrap"><table><thead id="thead"></thead><tbody id="tbody"></tbody></table></div>
<div class="empty" id="empty" hidden>No matching products.</div>

<script>
const ROWS = ${data};
const CATS = ${cats};
const PHARMS = ${pharms};
const COLS = [
  ["product_name","Product"],["strength","Strength"],["form","Form"],["package","Package"],
  ["pharmacy","Pharmacy"],["sku","SKU"],["wholesale_cost","Wholesale $"],["tags","Tags"],["notes","Notes"]
];
let activeCat = "All", sortKey = null, sortDir = 1;

const el = (id)=>document.getElementById(id);
function counts(cat){ return cat==="All"?ROWS.length:ROWS.filter(r=>r.category===cat).length; }

function renderTabs(){
  el("tabs").innerHTML = CATS.map(c =>
    '<span class="tab'+(c===activeCat?' active':'')+'" data-c="'+c+'">'+c+'<span class="n">'+counts(c)+'</span></span>'
  ).join("");
  el("tabs").querySelectorAll(".tab").forEach(t=>t.onclick=()=>{ activeCat=t.dataset.c; renderTabs(); render(); });
}
function renderHead(){
  el("thead").innerHTML = "<tr>"+COLS.map(([k,l])=>
    '<th class="'+(k==="wholesale_cost"?"num":"")+'" data-k="'+k+'">'+l+(sortKey===k?(sortDir>0?" ▲":" ▼"):"")+'</th>'
  ).join("")+"</tr>";
  el("thead").querySelectorAll("th").forEach(th=>th.onclick=()=>{
    const k=th.dataset.k; if(sortKey===k) sortDir*=-1; else {sortKey=k; sortDir=1;} render();
  });
}
function tagHtml(tags){ return tags? tags.split("|").filter(Boolean).map(t=>
  '<span class="tag'+(t==="review"?" review":"")+'">'+t+'</span>').join("") : ""; }

function render(){
  const q = el("q").value.trim().toLowerCase();
  const ph = el("pharm").value;
  const rxOnly = el("rx").checked;
  let rows = ROWS.filter(r=>{
    if(activeCat!=="All" && r.category!==activeCat) return false;
    if(ph!=="All" && r.pharmacy!==ph) return false;
    if(rxOnly && r.rx_required!=="yes") return false;
    if(q){
      const hay=(r.product_name+" "+r.active_ingredients+" "+r.sku+" "+r.strength+" "+r.tags+" "+r.notes).toLowerCase();
      if(!hay.includes(q)) return false;
    }
    return true;
  });
  if(sortKey){
    rows = rows.slice().sort((a,b)=>{
      let x=a[sortKey], y=b[sortKey];
      if(sortKey==="wholesale_cost"){ x=parseFloat(x)||0; y=parseFloat(y)||0; return (x-y)*sortDir; }
      return String(x).localeCompare(String(y))*sortDir;
    });
  }
  el("count").textContent = rows.length + " of " + ROWS.length + " products";
  el("empty").hidden = rows.length>0;
  el("tbody").innerHTML = rows.map(r=>"<tr>"+COLS.map(([k])=>{
    if(k==="tags") return "<td>"+tagHtml(r.tags)+"</td>";
    if(k==="wholesale_cost") return '<td class="num mono">'+(r[k]?"$"+r[k]:"")+"</td>";
    if(k==="product_name") return '<td>'+r[k]+(activeCat==="All"?' <span class="cat">· '+r.category+'</span>':'')+'</td>';
    if(k==="sku"||k==="strength"||k==="form") return '<td class="mono">'+r[k]+"</td>";
    return "<td>"+(r[k]||"")+"</td>";
  }).join("")+"</tr>").join("");
}

el("pharm").innerHTML = PHARMS.map(p=>'<option>'+p+'</option>').join("");
el("q").oninput = render; el("pharm").onchange = render; el("rx").onchange = render;
renderTabs(); renderHead(); render();
</script>
</body>
</html>
`;
  writeFileSync(join(ROOT, "index.html"), html);
}

function main() {
  const rows = loadRows(readFileSync(CSV_PATH, "utf8"));
  const byCat = groupByCategory(rows);
  writeJson(rows, byCat);
  writeMarkdown(rows, byCat);
  writeHtml(rows);
  const summary = FORMULARY_CATEGORIES.filter((c) => byCat[c].length)
    .map((c) => `${c}: ${byCat[c].length}`)
    .join(", ");
  console.log(`[build] ${rows.length} products — ${summary}`);
  console.log("[build] wrote formulary.json, FORMULARY.md, index.html");
}

main();
